<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>forge</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Terminal.Gui" />
    <ProjectReference Include="..\Forge.Bootstrap\Forge.Bootstrap.csproj" />
  </ItemGroup>
</Project>
