using Forge.Compiler;

namespace Forge.Providers.Claude;

/// <summary>
/// Generates Claude Code's native integration file (ADR 0010). Claude Code reads `CLAUDE.md` at
/// the project root and supports a `@&lt;path&gt;` import directive — this repository's own
/// `CLAUDE.md` already uses `@AGENTS.md` for exactly this purpose. The generated file stays thin
/// and imports Codex's `AGENTS.md` rather than duplicating the canonical body, so the two vendor
/// files can never diverge in content.
/// </summary>
public sealed class ClaudeIntegrationGenerator : IProviderIntegrationGenerator
{
    public ProviderId ProviderId { get; } = ClaudeLlmProvider.ClaudeCode;

    public GeneratedArtifact Generate(CanonicalIntegrationSource source)
    {
        ArgumentNullException.ThrowIfNull(source);
        string content =
            "<!-- Generated by Forge. Do not edit directly — edit .forge/rules/ or " +
            $".forge/knowledge/ instead. source_digest={source.SourceDigest} " +
            $"generator_version={source.GeneratorVersion} -->{Environment.NewLine}{Environment.NewLine}" +
            $"@AGENTS.md{Environment.NewLine}";
        return new(
            ProviderId,
            "CLAUDE.md",
            content,
            "text/markdown",
            "agent_facing",
            source.Language,
            source.SourceDigest,
            source.PolicySnapshotHash,
            source.GeneratorVersion);
    }
}
