<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <ProjectReference Include="..\Forge.Application\Forge.Application.csproj" />
    <ProjectReference Include="..\Forge.Configuration\Forge.Configuration.csproj" />
    <ProjectReference Include="..\Forge.Infrastructure\Forge.Infrastructure.csproj" />
    <ProjectReference Include="..\Forge.Localization\Forge.Localization.csproj" />
    <ProjectReference Include="..\Forge.Presentation\Forge.Presentation.csproj" />
    <ProjectReference Include="..\Forge.Providers\Forge.Providers.csproj" />
    <ProjectReference Include="..\Forge.Updater\Forge.Updater.csproj" />
  </ItemGroup>
</Project>
